### Default
GET http://localhost:5000/api/auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTM3MGMxNDY4MWQwNjQ3NDJkNzc4MjIiLCJpYXQiOjE2MzEwMDYxMzIsImV4cCI6MTYzMTAwNjE2Mn0.x5V0DBSstrYNE9Zru3wGAagew9Ajjvl-1tP4uSde72w


### Register
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "igdev",
  "password": "igdev"
}


### Login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "igdev",
  "password": "1"
}


### Louout
DELETE http://localhost:5000/api/auth/logout
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTMxZDg2OTU3N2YyZTIzYjFiMDA2M2MiLCJpYXQiOjE2MzA2Nzk3NjJ9.uH-9d4dYiKu7zCtWQynWcwmUHWh3pQKWLtl3Di4rZOQ"
}


### Get new token
POST http://localhost:5000/api/auth/token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTMxZDg2OTU3N2YyZTIzYjFiMDA2M2MiLCJpYXQiOjE2MzA2Nzk3NjJ9.uH-9d4dYiKu7zCtWQynWcwmUHWh3pQKWLtl3Di4rZOQ"
}
