### Get posts
GET http://localhost:5000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTNhMGIzMDRhMDM2YmI0ODJhNDk5YmEiLCJpYXQiOjE2MzEzMjc4MDEsImV4cCI6MTYzMTYyNzgwMX0.O7ZAOLqFuppvsQ9AYlsranjCtCsM0q2UziOviZ1iMR0


### Create new post
POST http://localhost:5000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTNhMGIzMDRhMDM2YmI0ODJhNDk5YmEiLCJpYXQiOjE2MzEzMjc4MDEsImV4cCI6MTYzMTYyNzgwMX0.O7ZAOLqFuppvsQ9AYlsranjCtCsM0q2UziOviZ1iMR0

{
  "content": "New post content2",
  "likeCount": 13120
}


### Update post
PUT http://localhost:5000/api/posts/613c3472b988a24a74147696
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTMxOWM0ZmFlMzk4NzExY2Y1NTE1MzciLCJpYXQiOjE2MzA2NTU4NDJ9.sOBmvlyN_PpmPMajzfNrSlmX1fi7WCAFbCK05opBHnY

{
  "content": "New post!!",
  "likeCount": "1234",
  "attachments": "random..."
}


### Delete post
DELETE http://localhost:5000/api/posts/613c4931b988a24a741476f7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTNhMGIzMDRhMDM2YmI0ODJhNDk5YmEiLCJpYXQiOjE2MzEzNDg1NjUsImV4cCI6MTYzMTY0ODU2NX0.yrattXbyFB37w2cb2EOy11j2Qt0ZMABd9SLajMSNhhA


### Like post
PATCH http://localhost:5000/api/posts/613c88a6663f087f63c02967
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTNhMGIzMDRhMDM2YmI0ODJhNDk5YmEiLCJpYXQiOjE2MzEzNDg1NjUsImV4cCI6MTYzMTY0ODU2NX0.yrattXbyFB37w2cb2EOy11j2Qt0ZMABd9SLajMSNhhA

{
  "likeCount": 12422212
}

